// Generated by Oraset3 Compiler
#include <iostream>
#include <string>
#include <vector>
#include <map>

using namespace std;

int main();
void println(int value);

int main() {
int x = 42    ;
int y = 18    ;
int sum = (x + y)    ;
println(sum)    ;
}

void println(int value) {
((std::cout << value) << std::endl)    ;
}

