#include "oraset3.h"
#include <sstream>
#include <cmath>

namespace oraset3 {

void CodeGenerator::emit(const std::string& str) {
    code += str;
}

void CodeGenerator::emitLine(const std::string& str) {
    for (int i = 0; i < indent; i++) {
        code += "    ";
    }
    code += str + "\n";
}

void CodeGenerator::indentUp() {
    indent++;
}

void CodeGenerator::indentDown() {
    indent--;
}

std::string CodeGenerator::generate(ProgramNode& program) {
    code = "";
    indent = 0;

    emitLine("// Generated by Oraset3 Compiler");
    emitLine("#include <iostream>");
    emitLine("#include <string>");
    emitLine("#include <vector>");
    emitLine("#include <map>");
    emitLine("#include <cmath>");
    emitLine("#include <fstream>");
    emitLine("#include <cstdio>");
    emitLine("#include <cstdlib>");
    emitLine("#include <sstream>");
    emitLine("#ifdef _WIN32");
    emitLine("#include <windows.h>");
    emitLine("#include <conio.h>");
    emitLine("#include <commdlg.h>");
    emitLine("#else");
    emitLine("#include <unistd.h>");
    emitLine("#include <sys/ioctl.h>");
    emitLine("#include <termios.h>");
    emitLine("#endif");
    emitLine("");
    emitLine("using namespace std;");
    emitLine("");
    emitLine("// 设置控制台编码为 UTF-8");
    emitLine("#ifdef _WIN32");
    emitLine("struct ConsoleInitializer {");
    emitLine("    ConsoleInitializer() {");
    emitLine("        SetConsoleOutputCP(65001);");
    emitLine("        SetConsoleCP(65001);");
    emitLine("    }");
    emitLine("};");
    emitLine("static ConsoleInitializer _consoleInit;");
    emitLine("#endif");
    emitLine("");

    // 输出内置函数声明
    emitLine("// Built-in functions");
    emitLine("void print(string value);");
    emitLine("void println(string value);");
    emitLine("void print(int value);");
    emitLine("void println(int value);");
    emitLine("void print(float value);");
    emitLine("void println(float value);");
    emitLine("void print(bool value);");
    emitLine("void println(bool value);");
    emitLine("");
    
    // 系统操作函数声明
    emitLine("// System functions");
    emitLine("int sys(string cmd);");
    emitLine("");
    
    // 文件操作函数声明
    emitLine("// File functions");
    emitLine("string file_read(string path);");
    emitLine("void file_write(string path, string content);");
    emitLine("bool file_exists(string path);");
    emitLine("");
    
    // 屏幕操作函数声明
    emitLine("// Screen functions");
    emitLine("void screen_clear();");
    emitLine("string screen_size();");
    emitLine("");
    
    // 绘图函数声明
    emitLine("// Draw functions");
    emitLine("void draw_text(int x, int y, string text);");
    emitLine("void draw_rect(int x, int y, int width, int height);");
    emitLine("void draw_line(int x1, int y1, int x2, int y2);");
    emitLine("void draw_set_color(int r, int g, int b);");
    emitLine("");
    
    // UI函数声明（仅当导入了sysui时）
    if (sysuiImported) {
        emitLine("// UI functions (sysui)");
        emitLine("void ui_msgbox(string title, string message);");
        emitLine("string ui_inputbox(string title, string prompt);");
        emitLine("void ui_alert(string message);");
        emitLine("bool ui_confirm(string message);");
        emitLine("string ui_prompt(string message);");
        emitLine("string ui_openfile();");
        emitLine("string ui_savefile();");
        emitLine("string ui_dir();");
        emitLine("void ui_color(int r, int g, int b);");
        emitLine("");
    }

    visit(program);

    // 输出内置函数实现
    emitLine("// Built-in function implementations");
    emitLine("void println(string s) { printf(\"%s\\n\", s.c_str()); }");
    emitLine("void print(string s) { printf(\"%s\", s.c_str()); }");
    emitLine("void print(int value) { printf(\"%d\", value); }");
    emitLine("void println(int value) { printf(\"%d\\n\", value); }");
    emitLine("void print(float value) { printf(\"%g\", value); }");
    emitLine("void println(float value) { printf(\"%g\\n\", value); }");
    emitLine("void print(bool value) { printf(\"%s\", value ? \"true\" : \"false\"); }");
    emitLine("void println(bool value) { printf(\"%s\\n\", value ? \"true\" : \"false\"); }");
    emitLine("");
    
    // 系统操作函数实现
    emitLine("// System function implementations");
    emitLine("int sys(string cmd) {");
    emitLine("    return system(cmd.c_str());");
    emitLine("}");
    emitLine("");
    
    // 文件操作函数实现
    emitLine("// File function implementations");
    emitLine("string file_read(string path) {");
    emitLine("    ifstream file(path);");
    emitLine("    if (!file) return \"\";");
    emitLine("    stringstream buffer;");
    emitLine("    buffer << file.rdbuf();");
    emitLine("    return buffer.str();");
    emitLine("}");
    emitLine("void file_write(string path, string content) {");
    emitLine("    ofstream file(path);");
    emitLine("    if (file) {");
    emitLine("        file << content;");
    emitLine("    }");
    emitLine("}");
    emitLine("bool file_exists(string path) {");
    emitLine("    ifstream file(path);");
    emitLine("    return file.good();");
    emitLine("}");
    emitLine("");
    
    // 屏幕操作函数实现
    emitLine("// Screen function implementations");
    emitLine("void screen_clear() {");
    emitLine("#ifdef _WIN32");
    emitLine("    system(\"cls\");");
    emitLine("#else");
    emitLine("    system(\"clear\");");
    emitLine("#endif");
    emitLine("}");
    emitLine("string screen_size() {");
    emitLine("#ifdef _WIN32");
    emitLine("    CONSOLE_SCREEN_BUFFER_INFO csbi;");
    emitLine("    GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &csbi);");
    emitLine("    int width = csbi.srWindow.Right - csbi.srWindow.Left + 1;");
    emitLine("    int height = csbi.srWindow.Bottom - csbi.srWindow.Top + 1;");
    emitLine("    return to_string(width) + \"x\" + to_string(height);");
    emitLine("#else");
    emitLine("    struct winsize w;");
    emitLine("    ioctl(STDOUT_FILENO, TIOCGWINSZ, &w);");
    emitLine("    return to_string(w.ws_col) + \"x\" + to_string(w.ws_row);");
    emitLine("#endif");
    emitLine("}");
    emitLine("");
    
    // 绘图函数实现
    emitLine("// Draw function implementations");
    emitLine("void draw_text(int x, int y, string text) {");
    emitLine("#ifdef _WIN32");
    emitLine("    COORD coord;");
    emitLine("    coord.X = x;");
    emitLine("    coord.Y = y;");
    emitLine("    SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE), coord);");
    emitLine("    printf(\"%s\", text.c_str());");
    emitLine("#else");
    emitLine("    printf(\"\\033[%d;%dH%s\", y+1, x+1, text.c_str());");
    emitLine("#endif");
    emitLine("}");
    emitLine("void draw_rect(int x, int y, int width, int height) {");
    emitLine("    for (int row = y; row < y + height; row++) {");
    emitLine("        for (int col = x; col < x + width; col++) {");
    emitLine("            if (row == y || row == y + height - 1 || col == x || col == x + width - 1) {");
    emitLine("                draw_text(col, row, \"*\");");
    emitLine("            }");
    emitLine("        }");
    emitLine("    }");
    emitLine("}");
    emitLine("void draw_line(int x1, int y1, int x2, int y2) {");
    emitLine("    int dx = abs(x2 - x1);");
    emitLine("    int dy = abs(y2 - y1);");
    emitLine("    int sx = (x1 < x2) ? 1 : -1;");
    emitLine("    int sy = (y1 < y2) ? 1 : -1;");
    emitLine("    int err = dx - dy;");
    emitLine("    int x = x1, y = y1;");
    emitLine("    while (true) {");
    emitLine("        draw_text(x, y, \".\");");
    emitLine("        if (x == x2 && y == y2) break;");
    emitLine("        int e2 = 2 * err;");
    emitLine("        if (e2 > -dy) { err -= dy; x += sx; }");
    emitLine("        if (e2 < dx) { err += dx; y += sy; }");
    emitLine("    }");
    emitLine("}");
    emitLine("void draw_set_color(int r, int g, int b) {");
    emitLine("#ifdef _WIN32");
    emitLine("    HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);");
    emitLine("    WORD color = ((r / 51) << 5) | ((g / 51) << 2) | (b / 51);");
    emitLine("    SetConsoleTextAttribute(hConsole, color);");
    emitLine("#else");
    emitLine("    printf(\"\\033[38;2;%d;%d;%dm\", r, g, b);");
    emitLine("#endif");
    emitLine("}");
    emitLine("");
    
    // UI函数实现（仅当导入了sysui时）
    if (sysuiImported) {
        emitLine("// UI function implementations (sysui)");
        emitLine("void ui_msgbox(string title, string message) {");
        emitLine("    printf(\"[Dialog] %s:\\n%s\\n\", title.c_str(), message.c_str());");
        emitLine("    printf(\"Press Enter to continue...\");");
        emitLine("    getchar();");
        emitLine("}");
        emitLine("string ui_inputbox(string title, string prompt) {");
        emitLine("    printf(\"[%s] %s: \", title.c_str(), prompt.c_str());");
        emitLine("    string input;");
        emitLine("    getline(cin, input);");
        emitLine("    return input;");
        emitLine("}");
        emitLine("void ui_alert(string message) {");
        emitLine("    printf(\"[Alert] %s\\n\", message.c_str());");
        emitLine("    printf(\"Press Enter to continue...\");");
        emitLine("    getchar();");
        emitLine("}");
        emitLine("bool ui_confirm(string message) {");
        emitLine("    printf(\"[Confirm] %s (y/n): \", message.c_str());");
        emitLine("    char c = getchar();");
        emitLine("    // 清除换行符");
        emitLine("    if (c != '\\n') getchar();");
        emitLine("    return (c == 'y' || c == 'Y');");
        emitLine("}");
        emitLine("string ui_prompt(string message) {");
        emitLine("    printf(\"%s: \", message.c_str());");
        emitLine("    string input;");
        emitLine("    getline(cin, input);");
        emitLine("    return input;");
        emitLine("}");
        emitLine("string ui_openfile() {");
        emitLine("    printf(\"[Open File] Enter file path: \");");
        emitLine("    string path;");
        emitLine("    getline(cin, path);");
        emitLine("    return path;");
        emitLine("}");
        emitLine("string ui_savefile() {");
        emitLine("    printf(\"[Save File] Enter file path: \");");
        emitLine("    string path;");
        emitLine("    getline(cin, path);");
        emitLine("    return path;");
        emitLine("}");
        emitLine("string ui_dir() {");
        emitLine("    printf(\"[Select Directory] Enter directory path: \");");
        emitLine("    string path;");
        emitLine("    getline(cin, path);");
        emitLine("    return path;");
        emitLine("}");
        emitLine("void ui_color(int r, int g, int b) {");
        emitLine("    draw_set_color(r, g, b);");
        emitLine("}");
        emitLine("");
    }

    return code;
}

void CodeGenerator::visit(ProgramNode& node) {
    bool hasMain = false;
    std::vector<ASTNode*> topLevelStmts;
    
    // 第一遍：输出所有结构体、接口、联合体和枚举声明
    for (auto& decl : node.declarations) {
        if (decl->getType() == NodeType::STRUCT_DECL || decl->getType() == NodeType::INTERFACE_DECL ||
            decl->getType() == NodeType::UNION_DECL || decl->getType() == NodeType::ENUM_DECL) {
            decl->accept(*this);
            emitLine("");
        }
    }
    
    // 第二遍：输出所有函数声明（原型）并收集顶层语句
    for (auto& decl : node.declarations) {
        if (decl->getType() == NodeType::FUNC_DECL) {
            FuncDeclNode& funcDecl = static_cast<FuncDeclNode&>(*decl);
            if (funcDecl.name == "main") {
                hasMain = true;
            }
            
            std::string returnType = funcDecl.returnType.empty() ? "void" : funcDecl.returnType;
            if (funcDecl.name == "main") {
                returnType = "int";
            }

            emit(returnType + " " + funcDecl.name + "(");
            for (size_t i = 0; i < funcDecl.params.size(); i++) {
                std::string paramType = funcDecl.params[i].second.empty() ? "auto" : funcDecl.params[i].second;
                emit(paramType + " " + funcDecl.params[i].first);
                if (i < funcDecl.params.size() - 1) {
                    emit(", ");
                }
            }
            emitLine(");");
        } else if (decl->getType() == NodeType::EXPR_STMT || decl->getType() == NodeType::VAR_DECL 
            || decl->getType() == NodeType::IF_STMT || decl->getType() == NodeType::WHILE_STMT 
            || decl->getType() == NodeType::FOR_STMT || decl->getType() == NodeType::RETURN_STMT) {
            // 收集顶层语句（包括控制流语句）
            topLevelStmts.push_back(decl.get());
        }
    }
    emitLine("");

    // 如果没有main函数且有顶层语句，自动生成main函数
    if (!hasMain && !topLevelStmts.empty()) {
        emitLine("int main() {");
        indentUp();
        for (auto* stmt : topLevelStmts) {
            stmt->accept(*this);
        }
        emitLine("return 0;");
        indentDown();
        emitLine("}");
        emitLine("");
    }

    // 第三遍：输出所有函数实现（跳过顶层语句和结构体/接口/联合体/枚举）
    for (auto& decl : node.declarations) {
        if (decl->getType() != NodeType::EXPR_STMT && decl->getType() != NodeType::VAR_DECL 
            && decl->getType() != NodeType::STRUCT_DECL && decl->getType() != NodeType::INTERFACE_DECL
            && decl->getType() != NodeType::UNION_DECL && decl->getType() != NodeType::ENUM_DECL
            && decl->getType() != NodeType::IF_STMT && decl->getType() != NodeType::WHILE_STMT 
            && decl->getType() != NodeType::FOR_STMT && decl->getType() != NodeType::RETURN_STMT) {
            decl->accept(*this);
            emitLine("");
        }
    }
}

void CodeGenerator::visit(VarDeclNode& node) {
    std::string type = node.type;

    // 如果没有指定类型且有初始化器，尝试推断类型
    if (type.empty() && node.initializer) {
        // 检查初始化器是否是字符串字面量
        if (node.initializer->getType() == NodeType::LITERAL_EXPR) {
            LiteralExprNode* lit = static_cast<LiteralExprNode*>(node.initializer.get());
            if (lit->type == "string") {
                type = "string";
            } else {
                type = "auto";
            }
        } else {
            type = "auto";
        }
    } else if (type.empty()) {
        type = "auto";
    }

    emit(type + " " + node.name);

    if (node.initializer) {
        emit(" = ");
        node.initializer->accept(*this);
    }

    emitLine(";");
}

void CodeGenerator::visit(FuncDeclNode& node) {
    std::string returnType = node.returnType.empty() ? "void" : node.returnType;
    if (node.name == "main") {
        returnType = "int";
    }
    emit(returnType + " " + node.name + "(");

    for (size_t i = 0; i < node.params.size(); i++) {
        std::string paramType = node.params[i].second.empty() ? "auto" : node.params[i].second;
        emit(paramType + " " + node.params[i].first);
        if (i < node.params.size() - 1) {
            emit(", ");
        }
    }

    emitLine(") {");
    indentUp();

    for (auto& stmt : node.body) {
        stmt->accept(*this);
    }

    indentDown();
    emitLine("}");
}

void CodeGenerator::visit(StructDeclNode& node) {
    emitLine("struct " + node.name + " {");
    indentUp();

    for (auto& field : node.fields) {
        std::string fieldType = field.second.empty() ? "auto" : field.second;
        emitLine(fieldType + " " + field.first + ";");
    }

    indentDown();
    emitLine("};");
}

void CodeGenerator::visit(InterfaceDeclNode& node) {
    emitLine("class " + node.name + " {");
    indentUp();
    emitLine("public:");
    indentUp();

    for (auto& method : node.methods) {
        std::string returnType = method.second.empty() ? "void" : method.second;
        emitLine("virtual " + returnType + " " + method.first + "() = 0;");
    }

    indentDown();
    indentDown();
    emitLine("};");
}

void CodeGenerator::visit(UnionDeclNode& node) {
    emitLine("union " + node.name + " {");
    indentUp();

    for (auto& field : node.fields) {
        std::string fieldType = field.second.empty() ? "auto" : field.second;
        emitLine(fieldType + " " + field.first + ";");
    }

    indentDown();
    emitLine("};");
}

void CodeGenerator::visit(EnumDeclNode& node) {
    emitLine("enum " + node.name + " {");
    indentUp();

    for (size_t i = 0; i < node.values.size(); i++) {
        auto& value = node.values[i];
        emit(value.first);
        if (!value.second.empty()) {
            emit(" = " + value.second);
        }
        if (i < node.values.size() - 1) {
            emit(",");
        }
        emitLine("");
    }

    indentDown();
    emitLine("};");
}

void CodeGenerator::visit(CastExprNode& node) {
    emit("(" + node.targetType + ")(");
    if (node.expr) {
        node.expr->accept(*this);
    }
    emit(")");
}

void CodeGenerator::visit(IfStmtNode& node) {
    emit("if (");
    node.condition->accept(*this);
    emitLine(") {");
    indentUp();

    for (auto& stmt : node.thenBranch) {
        stmt->accept(*this);
    }

    indentDown();
    emitLine("}");

    if (!node.elseBranch.empty()) {
        emit("else ");

        if (node.elseBranch.size() == 1 &&
            node.elseBranch[0]->getType() == NodeType::IF_STMT) {
            node.elseBranch[0]->accept(*this);
        } else {
            emitLine("{");
            indentUp();

            for (auto& stmt : node.elseBranch) {
                stmt->accept(*this);
            }

            indentDown();
            emitLine("}");
        }
    }
}

void CodeGenerator::visit(ForStmtNode& node) {
    emit("for (");

    if (node.init) {
        node.init->accept(*this);
    }
    emit("; ");

    if (node.condition) {
        node.condition->accept(*this);
    }
    emit("; ");

    if (node.update) {
        node.update->accept(*this);
    }

    emitLine(") {");
    indentUp();

    for (auto& stmt : node.body) {
        stmt->accept(*this);
    }

    indentDown();
    emitLine("}");
}

void CodeGenerator::visit(WhileStmtNode& node) {
    emit("while (");
    node.condition->accept(*this);
    emitLine(") {");
    indentUp();

    for (auto& stmt : node.body) {
        stmt->accept(*this);
    }

    indentDown();
    emitLine("}");
}

void CodeGenerator::visit(ReturnStmtNode& node) {
    emit("return");

    if (node.expr) {
        emit(" ");
        node.expr->accept(*this);
    }

    emitLine(";");
}

void CodeGenerator::visit(ExprStmtNode& node) {
    node.expr->accept(*this);
    emitLine(";");
}

void CodeGenerator::visit(AssignExprNode& node) {
    node.left->accept(*this);
    emit(" " + node.op + " ");
    node.right->accept(*this);
}

void CodeGenerator::visit(BinaryExprNode& node) {
    emit("(");
    node.left->accept(*this);
    emit(" " + node.op + " ");
    node.right->accept(*this);
    emit(")");
}

void CodeGenerator::visit(UnaryExprNode& node) {
    emit(node.op);
    node.operand->accept(*this);
}

void CodeGenerator::visit(CallExprNode& node) {
    // 检查是否是特殊的系统函数调用
    std::string funcName;
    
    if (node.callee->getType() == NodeType::IDENTIFIER_EXPR) {
        IdentifierExprNode* ident = static_cast<IdentifierExprNode*>(node.callee.get());
        funcName = ident->name;
    } else if (node.callee->getType() == NodeType::MEMBER_EXPR) {
        MemberExprNode* member = static_cast<MemberExprNode*>(node.callee.get());
        if (member->object->getType() == NodeType::IDENTIFIER_EXPR) {
            IdentifierExprNode* objIdent = static_cast<IdentifierExprNode*>(member->object.get());
            funcName = objIdent->name + "." + member->property;
        }
    }
    
    // 处理系统函数调用的转换
    if (funcName == "sys") {
        emit("sys(");
    } else if (funcName == "file.read") {
        emit("file_read(");
    } else if (funcName == "file.write") {
        emit("file_write(");
    } else if (funcName == "file.exists") {
        emit("file_exists(");
    } else if (funcName == "screen.clear") {
        emit("screen_clear(");
    } else if (funcName == "screen.size") {
        emit("screen_size(");
    } else if (funcName == "draw.text") {
        emit("draw_text(");
    } else if (funcName == "draw.rect") {
        emit("draw_rect(");
    } else if (funcName == "draw.line") {
        emit("draw_line(");
    } else if (funcName == "draw.color") {
        emit("draw_set_color(");
    } else if (funcName == "ui.msgbox") {
        emit("ui_msgbox(");
    } else if (funcName == "ui.inputbox") {
        emit("ui_inputbox(");
    } else if (funcName == "ui.alert") {
        emit("ui_alert(");
    } else if (funcName == "ui.confirm") {
        emit("ui_confirm(");
    } else if (funcName == "ui.prompt") {
        emit("ui_prompt(");
    } else if (funcName == "ui.openfile") {
        emit("ui_openfile(");
    } else if (funcName == "ui.savefile") {
        emit("ui_savefile(");
    } else if (funcName == "ui.dir") {
        emit("ui_dir(");
    } else if (funcName == "ui.color") {
        emit("ui_color(");
    } else {
        node.callee->accept(*this);
        emit("(");
    }

    for (size_t i = 0; i < node.args.size(); i++) {
        // 如果参数是字符串字面量，包装为 string() 以确保正确的函数重载
        if (node.args[i]->getType() == NodeType::LITERAL_EXPR) {
            LiteralExprNode* lit = static_cast<LiteralExprNode*>(node.args[i].get());
            if (lit->type == "string") {
                emit("string(");
            }
        }
        node.args[i]->accept(*this);
        if (node.args[i]->getType() == NodeType::LITERAL_EXPR) {
            LiteralExprNode* lit = static_cast<LiteralExprNode*>(node.args[i].get());
            if (lit->type == "string") {
                emit(")");
            }
        }
        if (i < node.args.size() - 1) {
            emit(", ");
        }
    }

    emit(")");
}

void CodeGenerator::visit(IndexExprNode& node) {
    node.base->accept(*this);
    emit("[");
    node.index->accept(*this);
    emit("]");
}

void CodeGenerator::visit(MemberExprNode& node) {
    node.object->accept(*this);
    emit(node.op + node.property);
}

void CodeGenerator::visit(StructInitNode& node) {
    emit(node.typeName + "{");
    for (size_t i = 0; i < node.fields.size(); i++) {
        emit("." + node.fields[i].first + " = ");
        node.fields[i].second->accept(*this);
        if (i < node.fields.size() - 1) {
            emit(", ");
        }
    }
    emit("}");
}

void CodeGenerator::visit(LiteralExprNode& node) {
    if (node.type == "string") {
        emit("\"" + node.value + "\"");
    } else {
        emit(node.value);
    }
}

void CodeGenerator::visit(IdentifierExprNode& node) {
    emit(node.name);
}

} // namespace oraset3
